name: stickereditor
description: A new Sticker plugin
version: 0.0.1
homepage: https://github.com/Harsh-Radadiya/sticker_editor/blob/master/example/lib/main.dart
repository: https://github.com/Harsh-Radadiya/sticker_editor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"


dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  dotted_border: ^2.0.0+1
  screenshot: ^1.2.3
  path_provider: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.stickereditor.stickereditor
        pluginClass: StickereditorPlugin
      ios:
        pluginClass: StickereditorPlugin
      macos:
        pluginClass: StickereditorPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/
    - assets/Stickers/
    # - assets/Stickers/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Light.ttf
    - family: PoiretOne
      fonts:
        - asset: fonts/PoiretOne-Regular.ttf
    - family: Monoton
      fonts:
        - asset: fonts/Monoton-Regular.ttf
    - family: BungeeInline
      fonts:
        - asset: fonts/BungeeInline-Regular.ttf
    - family: ConcertOne
      fonts:
        - asset: fonts/ConcertOne-Regular.ttf
    - family: FrederickatheGreat
      fonts:
        - asset: fonts/FrederickatheGreat-Regular.ttf
    - family: Martel
      fonts:
        - asset: fonts/Martel-ExtraLight.ttf
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
    - family: Vidaloka
      fonts:
        - asset: fonts/Vidaloka-Regular.ttf
    - family: Billabong
      fonts:
        - asset: fonts/Billabong.ttf
    - family: GrandHotel
      fonts:
        - asset: fonts/GrandHotel.otf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans.ttf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand.otf
    - family: BeautifulPeople
      fonts:
        - asset: fonts/BeautifulPeople.ttf
    - family: BeautyMountains
      fonts:
        - asset: fonts/BeautyMountains.ttf
    - family: BiteChocolate
      fonts:
        - asset: fonts/BiteChocolate.ttf
    - family: BlackberryJam
      fonts:
        - asset: fonts/BlackberryJam.ttf
    - family: Tomatoes
      fonts:
        - asset: fonts/Tomatoes.ttf
    - family: BunchBlossoms
      fonts:
        - asset: fonts/BunchBlossoms.ttf
    - family: CinderelaRegular
      fonts:
        - asset: fonts/CinderelaRegular.ttf
    - family: Countryside
      fonts:
        - asset: fonts/Countryside.ttf
    - family: Halimun
      fonts:
        - asset: fonts/Halimun.ttf
    - family: LemonJelly
      fonts:
        - asset: fonts/LemonJelly.ttf
    - family: QuiteMagicalRegular
      fonts:
        - asset: fonts/QuiteMagicalRegular.ttf
    - family: TropicalAsianDemoRegular
      fonts:
        - asset: fonts/TropicalAsianDemoRegular.ttf
    - family: VeganStyle
      fonts:
        - asset: fonts/VeganStyle.ttf
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
